#! /bin/bash

#EDIT YOUR STAGING CREDENTIALS HERE
staginghost=""
stagingpswd=""
staginguser=""

#EDIT YOUR PRODUCTION CREDENTIALS HERE
productionhost=""
productionpswd=""
productionuser=""

#DONT TOUCH THIS
echo "Do you want to init the project? [yes or no]"
read init

echo "Where to deploy? [staging or production]"
read environment

if [ "$init" == "yes" ]; then
	if [ "$environment" == "staging" ]; then
		git ftp init -u "$staginguser" -P "$staginghost"
	fi
	if [ "$environment" == "production" ]; then
		git ftp init -u "$productionuser" -P "$productionhost"
	fi
fi

if [ "$init" == "no" ]; then
	if [ "$environment" == "staging" ]; then
		git ftp push --user "$staginguser" --passwd "$stagingpswd" "$staginghost"
	fi
	if [ "$environment" == "production" ]; then
		git ftp push --user "$productionuser" --passwd "$productionpswd" "$productionhost"
	fi
fi

if [ "$init" == "yes" ]; then
	echo init to $environment;
else
	echo update to $environment;
fi
